appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZNd5sYN6rxRa8QvZ74yc+E5fTl4osWPRU5J+4Uv6XYDugK3qEMCqe9+e4ZN4PgIWj6OTHOs47a6wsmdnRODNPeJanIOoZHTrvXEXMx0k5LIrNDpzD0woydPkBvJW5Bo8CDxPu5XQtStjODuQtA/VT23FlKgTRcFUwslqXrDl1BQNje6vKLe4gdcVcL0XxgX9gugbW60LKxtuD/uDd5lMjVU0nnOJjdwIN/GibRp6/IMoYuzVbs1hyD1/X8h02NgvbjcIEtCJat49zqEDRVh/aCvsxDYcJrTk2dgojrKRIEzK32i25LMBiYPdjLdaSFoz9cs+T87I3p2yRBVnHqnxl9TypZkf60FXvqYbLcPzBTZohHTe0Cvu+6qHs8Y9ZQphDX7DuIxGPMkfY8yCtc5E+zz8SvFtss8WktQ9TNN03SidQkcsCMkmqDDknirPTkqnIAce43V+AqDKIRNz3BK9PAFzUlVMg/8tb3HA0NvSvAbrevF1+c7psRG3NYstfKtJ0cobBJ/+yAA3AnCtNHRNdQHXEnGWDiyshRix0Y4SkAAbxGYcwa1p9A3qGKwZ+hHhvsn6e4DKp8udiGqoxWiEmx/WQikkSPpDWJ6WbXF7wXaE4oq5L2M2UlwgfFt5TyIfrouvxyTG0jBMz6cgYCycb7k1ovb1w2SKUl6Yp9iyTXk=
conda_forge_output_validation: false
